### ISSUE TITLE
External Ingress and Update api version

### ISSUE THREAD

**Issue by defied** [jmcdice/k8s-ubuntu-desktop#6]

**Comment by defied** [comment]
Change Deployment apiVersion:
`apiVersion: apps/v1`

Change service to ClusterIP:
```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ubuntu-desktop
  name: ubuntu-desktop
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: ubuntu-desktop
  type: ClusterIP
```

Add ubuntu-desktop-ingress.yml:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ubuntu-desktop
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ubuntu-desktop
            port:
              number: 80
    host: host.example.com
```
